# Absolute path on Linux (adjust /home/youruser/ as needed)
spring.datasource.url=jdbc:sqlite:prod_database.db?foreign_keys=on

# In Prod, we might want to be more careful with schema changes
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# Keep prod clean from mock data
app.seeding.enabled=false