# Local relative path
spring.datasource.url=jdbc:sqlite:dev_database.db

# In Dev, we want to see the SQL and update tables automatically
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Custom property to control your seeder
app.seeding.enabled=true