name: Build and Deploy Backend to Pi

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25
          cache: maven

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      - name: Install Cloudflared
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb -o cloudflared.deb
          sudo dpkg -i cloudflared.deb

      - name: Detect DB Changes
        id: dbcheck
        run: |
          if git diff --name-only \
            ${{ github.event.before }} \
            ${{ github.sha }} | grep '^src/main/resources/db/'; then
            echo "db_changed=true" >> $GITHUB_OUTPUT
          else
            echo "db_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Deploy to Pi via Rsync
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          CF_ID: ${{ secrets.CF_CLIENT_ID }}
          CF_SECRET: ${{ secrets.CF_CLIENT_SECRET }}
          PI_USER: ${{ secrets.PI_USERNAME }}
          PI_HOST: ${{ secrets.PI_HOST }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          rsync -avz -e "ssh -o StrictHostKeyChecking=no -o 'ProxyCommand=cloudflared access ssh --hostname %h --service-token-id $CF_ID --service-token-secret $CF_SECRET'" \
            ./target/*.jar $PI_USER@$PI_HOST:/home/$PI_USER/hytrac/backend/

      - name: Restart Backend Service
        env:
          CF_ID: ${{ secrets.CF_CLIENT_ID }}
          CF_SECRET: ${{ secrets.CF_CLIENT_SECRET }}
          PI_USER: ${{ secrets.PI_USERNAME }}
          PI_HOST: ${{ secrets.PI_HOST }}
        run: |
          ssh -o StrictHostKeyChecking=no -o "ProxyCommand=cloudflared access ssh --hostname %h --service-token-id $CF_ID --service-token-secret $CF_SECRET" \
            $PI_USER@$PI_HOST "sudo systemctl restart hytrac-backend.service"

      - name: Cleanup DB if Schema Changed + Restart Backend
        env:
          CF_ID: ${{ secrets.CF_CLIENT_ID }}
          CF_SECRET: ${{ secrets.CF_CLIENT_SECRET }}
          PI_USER: ${{ secrets.PI_USERNAME }}
          PI_HOST: ${{ secrets.PI_HOST }}
          DB_CHANGED: ${{ steps.dbcheck.outputs.db_changed }}
        run: |

          ssh -o StrictHostKeyChecking=no \
            -o "ProxyCommand=cloudflared access ssh --hostname %h --service-token-id $CF_ID --service-token-secret $CF_SECRET" \
            $PI_USER@$PI_HOST "

              cd /home/$PI_USER/hytrac/backend

              if [ \"$DB_CHANGED\" = \"true\" ]; then
                echo 'DB schema changed. Removing SQLite DB files...'
                rm -f ./*.db
              fi

              sudo systemctl restart hytrac-backend.service
            "